### ISSUE TITLE
CustomPropertyDrawer not working (unity 2019.3) 

### ISSUE THREAD

**Issue by morgoth990** [Demigiant/demilib#13]
Writing a CustomPropertyDrawer (documented in the page https://docs.unity3d.com/ScriptReference/PropertyDrawer.html) is not working.
I've tried the same code in an empty project without demilib and is working.

**Comment by Demigiant** [comment]
I have some CustomPropertyDrawers working right now in Unity 2019.3 and DemiLib included. Is it possible that you're importing some wrong namespace?

**Comment by morgoth990** [comment]
Ok, I've restarted unity and now is working... facepalm
