### ISSUE TITLE
DeInspektor for ScriptableObject

### ISSUE THREAD

**Issue by zyzyxdev** [Demigiant/demilib#3]
Hi, 
just downloaded DeInspektor and it works great for Components. Are there plans to make it work for ScriptableObject inspectors too?

**Comment by Demigiant** [comment]
Ah, silly me, I never use regular Inspector with ScriptableObjects so I didn't check that. Going to see about it asap.

**Comment by Demigiant** [comment]
Ahoy again. I just opened the project and realized I don't really know how you would want to use this with ScriptableObjects. I mean, SO are usually used as variables inside MonoBehaviours/SOs, or otherwise with a custom Inspector, since there is no auto-inspector for them. Can you tell me more, maybe I'm missing something.

**Comment by zyzyxdev** [comment]
Sure!
After creating a SO it exists as an asset file. Selecting it draws the inspector as it would on a Monobehavior.
Example:
```using UnityEngine;

[CreateAssetMenu(fileName = "Case", menuName = "SecurityGame/Case", order = 2)]
public class Case : ScriptableObject 
{
	public int Id;
	public int Budget;
	[TextArea(1, 6)]
	public string InfoText;
	[TextArea(1, 6)]
	public string HackingInfoText;
	[TextArea(1, 6)]
	public string HackedText;
	public int[] AvailableTools;
}
```

![scriptableobject](https://cloud.githubusercontent.com/assets/2347127/23665776/b41c77ae-0359-11e7-8ce4-643af9aa22cb.PNG)
![scriptableobject_2](https://cloud.githubusercontent.com/assets/2347127/23665997/598a8f14-035a-11e7-9181-fcda6e8c8686.PNG)

**Comment by Demigiant** [comment]
Ah, I see. I always made custom editors for them so never thought of this. Done! You can grab the new update from the downloads section ;)
