### ISSUE TITLE
[Header("MyHeader")] does not work if declared after array.

### ISSUE THREAD

**Issue by grayworks** [Demigiant/demilib#4]
It is DeInspektor issue.
If I put HeaderAttribute after an array, it does not work.
For example:
```
[SerializeField] BlockerData[] blockers;
[Header("Switcher")]
```
If some public variable is declared between them (even hidden), it works fine. 
Custom enum type works, but if I declare `public float someVar;`, the problem is still here.

[DeHeader] has the same problem.

**Comment by Demigiant** [comment]
Ahoy!

That is weird, I just tried with both Header and DeHeader and they work correctly here after an array. Can you try to update to the latest version and see if it still happens to you? Otherwise, can you tell me on what Unity version are you, and attach a MonoBehaviour that replicates this issue?

**Comment by grayworks** [comment]
Hey!
Looks like the reason of this behaviour is a [HideInInspector] attribute.
I reproduced this issue with Unity 5.5.2f1 and latest version of the extensions.
DOTween v1.1.555
DemiLib_Complete from the latest commit.
[DaInspAssets.zip](https://github.com/Demigiant/demilib/files/888315/Assets.zip)
[DaInspScreen.png](https://cloud.githubusercontent.com/assets/3100945/24586597/7ea25af4-17ad-11e7-98db-093c40665b39.png)

**Comment by Demigiant** [comment]
Ahoy!
Sorry, I completely missed your reply. Thanks for the clarification, didn't think of that. That is by Unity design I'm afraid (the same happens if you use Unity's own Header attribute): moving the DeHeader under the inspector-hidden property will work though.
Cheers!
