### ISSUE TITLE
Order not respected

### ISSUE THREAD

**Issue by RDeluxe** [Demigiant/demilib#8]
Hey there

I have been having some troubles with DeComment not respecting the order.

![unity_2017-11-16_19-35-56](https://user-images.githubusercontent.com/2767681/32908954-82a580de-cb05-11e7-9156-6a2d4a1e8906.png)

Here is the code : 

``` csharp
        [DeHeader("Generic skills properties", mode = DeHeaderAttribute.Mode.BottomDivider)]
        [DeComment("Launch passively, disable the button to launch in UI")]
        [DeDivider]
        public bool Passive;
```

If I revert them everything is fine:

![unity_2017-11-16_19-39-08](https://user-images.githubusercontent.com/2767681/32909065-d5d7f836-cb05-11e7-90b9-ba74e3e47315.png)

``` csharp
        [DeDivider]
        [DeComment("Launch passively, disable the button to launch in UI")]
        [DeHeader("Generic skills properties", mode = DeHeaderAttribute.Mode.BottomDivider)]
        public bool Passive;
```

Note: using only DeComment and DeHeader, order is screwed too. Same thing with DeComment + DeDivider

![unity_2017-11-16_19-41-17](https://user-images.githubusercontent.com/2767681/32909171-2ad954b0-cb06-11e7-839c-ae3f0dc3e79c.png)

``` csharp
        [DeHeader("Generic skills properties", mode = DeHeaderAttribute.Mode.BottomDivider)]
        [DeComment("Launch passively, disable the button to launch in UI")]
        public bool Passive;
```

**Comment by Demigiant** [comment]
That is weird :O Checking it out!

**Comment by Demigiant** [comment]
Uh, it gets weirder. Everything works perfectly here, and order is respected (though I'm testing on Unity 5.6.3). Also, I checked the code and the order is decided by Unity, which should just call GetHeight and OnGUI of those drawers in the order they're drawn, so it seems Unity is messing something up there. On what version are you?

**Comment by RDeluxe** [comment]
Hm, using 2017.2 with .NET 4.6

**Comment by Demigiant** [comment]
In theory there is an extra order parameter on all attributes that you can use, to force the draw order:
[DeComment

**Comment by Demigiant** [comment]
In theory there is an extra order parameter on all attributes that you can use, to force the draw order:
`[DeComment("dum dee dum very useful comment", order = 1)]`

I'm assuming that in pre-2017 versions Unity ordered stuff correctly even if you left it to the default 0, while in 2017 order is now broken and you should set it manually :( Can you try and let me know (I don't want to make a 2017 copy of the DemiLib project just for this, if I can avoid it :P)

**Comment by Demigiant** [comment]
P.S. even so, I hope this is just a 2017.2 issue (since 2017.2 brought a lot of bugs) and it will be fixed in the next one?

**Comment by RDeluxe** [comment]
Thanks, it's working great with the order parameter !

Let's hope it's 2017.2 !

**Comment by Demigiant** [comment]
Crossing my fingers!
