### ISSUE TITLE
UIExtensions simplification

### ISSUE THREAD

**Issue by karsion** [Demigiant/demilib#9]
Hi!
UIExtensions use UnityEngine.UI.Graphic to SetAlpha or SetColor
UnityEngine.UI.Graphic is a parent class  of many ui classes.

SetAlpha be equal to SetFade match with DOFade

**Comment by Demigiant** [comment]
Ahoy!

Done and pushed :) I actually just added Graphic extensions, without removing the Image ones. Because in case you do want to set an Image it's faster if you have an extension that references that exact type directly.

Cheers,
Daniele
